# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: langchain.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'langchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flangchain.proto\x12\tlangchain\"\x1f\n\tUserQuery\x12\x12\n\nquery_text\x18\x01 \x01(\t\"$\n\rChatbotAnswer\x12\x13\n\x0b\x61nswer_text\x18\x01 \x01(\t\"3\n\x14SemanticSearchResult\x12\x1b\n\x13\x66ound_documents_ids\x18\x01 \x03(\x03\"\x0e\n\x0c\x45mptyRequest\"1\n\x12RecommendedPrompts\x12\x1b\n\x13recommended_prompts\x18\x01 \x03(\t2\xe2\x01\n\tLangChain\x12@\n\x0eGenerateAnswer\x12\x14.langchain.UserQuery\x1a\x18.langchain.ChatbotAnswer\x12G\n\x0eSemanticSearch\x12\x14.langchain.UserQuery\x1a\x1f.langchain.SemanticSearchResult\x12J\n\x10RecommendPrompts\x12\x17.langchain.EmptyRequest\x1a\x1d.langchain.RecommendedPromptsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'langchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERQUERY']._serialized_start=30
  _globals['_USERQUERY']._serialized_end=61
  _globals['_CHATBOTANSWER']._serialized_start=63
  _globals['_CHATBOTANSWER']._serialized_end=99
  _globals['_SEMANTICSEARCHRESULT']._serialized_start=101
  _globals['_SEMANTICSEARCHRESULT']._serialized_end=152
  _globals['_EMPTYREQUEST']._serialized_start=154
  _globals['_EMPTYREQUEST']._serialized_end=168
  _globals['_RECOMMENDEDPROMPTS']._serialized_start=170
  _globals['_RECOMMENDEDPROMPTS']._serialized_end=219
  _globals['_LANGCHAIN']._serialized_start=222
  _globals['_LANGCHAIN']._serialized_end=448
# @@protoc_insertion_point(module_scope)
