# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import langchain_pb2 as langchain__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in langchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LangChainStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAnswer = channel.unary_unary(
                '/langchain.LangChain/GenerateAnswer',
                request_serializer=langchain__pb2.UserQuery.SerializeToString,
                response_deserializer=langchain__pb2.ChatbotAnswer.FromString,
                _registered_method=True)
        self.SemanticSearch = channel.unary_unary(
                '/langchain.LangChain/SemanticSearch',
                request_serializer=langchain__pb2.UserQuery.SerializeToString,
                response_deserializer=langchain__pb2.SemanticSearchResult.FromString,
                _registered_method=True)
        self.RecommendPrompts = channel.unary_unary(
                '/langchain.LangChain/RecommendPrompts',
                request_serializer=langchain__pb2.EmptyRequest.SerializeToString,
                response_deserializer=langchain__pb2.RecommendedPrompts.FromString,
                _registered_method=True)


class LangChainServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SemanticSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecommendPrompts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LangChainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAnswer,
                    request_deserializer=langchain__pb2.UserQuery.FromString,
                    response_serializer=langchain__pb2.ChatbotAnswer.SerializeToString,
            ),
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=langchain__pb2.UserQuery.FromString,
                    response_serializer=langchain__pb2.SemanticSearchResult.SerializeToString,
            ),
            'RecommendPrompts': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendPrompts,
                    request_deserializer=langchain__pb2.EmptyRequest.FromString,
                    response_serializer=langchain__pb2.RecommendedPrompts.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'langchain.LangChain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('langchain.LangChain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LangChain(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langchain.LangChain/GenerateAnswer',
            langchain__pb2.UserQuery.SerializeToString,
            langchain__pb2.ChatbotAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langchain.LangChain/SemanticSearch',
            langchain__pb2.UserQuery.SerializeToString,
            langchain__pb2.SemanticSearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecommendPrompts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/langchain.LangChain/RecommendPrompts',
            langchain__pb2.EmptyRequest.SerializeToString,
            langchain__pb2.RecommendedPrompts.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
