# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tag_recommender.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tag_recommender.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tag_recommender.proto\x12\x0ftag_recommender\"B\n\x18TagRecommendationRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\x03\x12\x15\n\rexisting_tags\x18\x02 \x03(\t\"+\n\x0fRecommendedTags\x12\x18\n\x10recommended_tags\x18\x01 \x03(\t2n\n\x0eTagRecommender\x12\\\n\rRecommendTags\x12).tag_recommender.TagRecommendationRequest\x1a .tag_recommender.RecommendedTagsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tag_recommender_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGRECOMMENDATIONREQUEST']._serialized_start=42
  _globals['_TAGRECOMMENDATIONREQUEST']._serialized_end=108
  _globals['_RECOMMENDEDTAGS']._serialized_start=110
  _globals['_RECOMMENDEDTAGS']._serialized_end=153
  _globals['_TAGRECOMMENDER']._serialized_start=155
  _globals['_TAGRECOMMENDER']._serialized_end=265
# @@protoc_insertion_point(module_scope)
