# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: langchain.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'langchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flangchain.proto\x12\tlangchain\"\x1f\n\tUserQuery\x12\x12\n\nquery_text\x18\x01 \x01(\t\"\"\n\x0bQueryAnswer\x12\x13\n\x0b\x61nswer_text\x18\x01 \x01(\t2H\n\tLangChain\x12;\n\x0b\x41nswerQuery\x12\x14.langchain.UserQuery\x1a\x16.langchain.QueryAnswerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'langchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERQUERY']._serialized_start=30
  _globals['_USERQUERY']._serialized_end=61
  _globals['_QUERYANSWER']._serialized_start=63
  _globals['_QUERYANSWER']._serialized_end=97
  _globals['_LANGCHAIN']._serialized_start=99
  _globals['_LANGCHAIN']._serialized_end=171
# @@protoc_insertion_point(module_scope)
