components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        grpc-blocking-task-processor:
            worker_threads: $worker-grpc-threads
            thread_name: grpc-worker

    default_task_processor: main-task-processor

    components:                       

        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-api-register:
            path: /auth/register
            method: POST
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
            
        handler-post-api-login:
            path: /auth/login
            method: POST
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-history:
            path: /history
            method: GET
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-notes:
            path: /notes
            method: POST
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
            
        handler-get-note-id:
            path: /notes/{note_id}
            method: GET
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-patch-note-id:
            path: /notes/{note_id}
            method: PATCH
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-tags-create:
            path: /tags/create
            method: POST
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-tags-all:
            path: /tags/all
            method: GET
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-tags-note:
            path: /tags/{note_id}
            method: GET
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-tags-note-tag:
            path: /tags/{note_id}/{tag_id}
            method: POST
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-tags-note-tag:
            path: /tags/{note_id}/{tag_id}
            method: DELETE
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-checklist-note:
            path: /checklist/{note_id}
            method: POST
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-get-checklist:
            path: /checklist/{checklist_id}
            method: GET
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-checklist:
            path: /checklist/{checklist_id}
            method: DELETE
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-patch-checklist:
            path: /checklist/{checklist_id}
            method: PATCH
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-post-checklist-item:
            path: /checklist/{checklist_id}/item
            method: POST
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-patch-checklist-item:
            path: /checklist/item/{item_id}
            method: PATCH
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-delete-checklist-item:
            path: /checklist/item/{item_id}
            method: DELETE
            auth:
                types:
                - bearer
                required: true
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
        postgres-db-1:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        secdist: {}
        default-secdist-provider:
            config: 'configs/jwt_config.json'
            
        dns-client:
            fs-task-processor: fs-task-processor
